
import { LanguageData, PresaleData, NavLinkItem, VisionCardData, EcosystemCardData, MembershipTierData, TokenDistributionItem, RoadmapItemData, AmbassadorTierData, ContactPoint, SocialLink, FooterSection, CrowdfundingFeatureData, CrowdfundingProjectData } from './types';

// === BSC Network Configuration ===
export const BSC_CHAIN_ID = 56;
export const BSC_CHAIN_ID_HEX = '0x38';

export const BSC_NETWORK_CONFIG = {
  chainId: BSC_CHAIN_ID_HEX,
  chainName: 'BNB Smart Chain',
  nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
  rpcUrls: ['https://bsc-dataseed.binance.org/', 'https://bsc-dataseed1.defibit.io/'],
  blockExplorerUrls: ['https://bscscan.com'],
};

export const PRESALE_CONTRACT_ADDRESS = '0xf012e31eFDC2485285E2E27175fa9397dF372bf7';
export const SALE_TOKEN_ADDRESS = '0x8A9f07fdBc75144C9207373597136c6E280A872D';
export const USDT_BSC_ADDRESS = '0x55d398326f99059fF775485246999027B3197955';
export const USDC_BSC_ADDRESS = '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d';
export const STABLE_DECIMALS = 18;
export const BSCSCAN_TX_URL = 'https://bscscan.com/tx/';
export const BSCSCAN_ADDRESS_URL = 'https://bscscan.com/address/';

export const TOKEN_PRICE = 0.12;

export const PRESALE_DATA: PresaleData = {
    targetUSD: 80000000,
    raisedUSD: 36000000, // Example value
    totalPresaleTokens: 400000000,
    endDate: new Date(Date.UTC(2026, 11, 31, 23, 59, 59)),
    bonusTiers: []
};


export const NAV_LINKS: NavLinkItem[] = [
  { href: "#vision", key: "navVision" },
  { href: "#ecosystem", key: "navEcosystem" },
  { href: "#crowdfunding", key: "navCrowdfunding" },
  { href: "#membership", key: "navMembership" },
  { href: "#presale", key: "navPresale", isActive: true },
  { href: "#roadmap", key: "navRoadmap" },
  { href: "#ambassadors", key: "navAmbassadors" },
  { href: "#contact", key: "navContact" },
];

export const LANGUAGES = [
  { code: 'es', name: 'Español' },
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'ar', name: 'العربية' },
  { code: 'ru', name: 'Русский' },
  { code: 'zh', name: '简体中文' },
];

export const TRANSLATIONS: LanguageData = {
  es: {
    navVision: "Visión", navEcosystem: "Ecosistema", navCrowdfunding: "Crowdfunding P2P", navMembership: "Membresía", navPresale: "Presale", navRoadmap: "Roadmap", navAmbassadors: "Embajadores", navContact: "Contacto",
    btnConnectWallet: "Pagar usando crypto", srOpenMenu: "Abrir menú principal",
    heroTitleBrand: "DRACMA", heroTitlePhoenix: "El Futuro del Valor, Hoy.",
    heroSubtitle: "Un holding Web3 de vanguardia que fusiona IA, Blockchain y Activos Reales tokenizados. Invierte de forma inteligente y transparente en la nueva economía.",
    btnJoinPresale: "Comprar ahora", btnExplore: "Explorar Ecosistema",
    visionTitle: "Nuestra Visión: Forjando el Mañana, Juntos",
    visionSubtitle: "En DRACMA, creemos en un futuro financiero más accesible, transparente y justo. No solo imaginamos este futuro, lo estamos construyendo activamente. Somos un equipo de innovadores, estrategas y tecnólogos con una misión clara: crear un Holding Empresarial Descentralizado que sirva como puente entre la solidez de los activos tradicionales y el potencial ilimitado de la Web3.\nUtilizamos la Inteligencia Artificial para optimizar y la Blockchain para asegurar, transformando activos del mundo real (RWA) —como oro, bienes raíces, energía renovable y agricultura sostenible— en oportunidades de inversión líquidas y verificables.\nNuestra meta es simple: empoderarte. Ofrecerte las herramientas y la plataforma para que participes en la nueva economía de valor, de forma informada y con confianza. DRACMA es más que un proyecto; es una comunidad que invierte en un mañana más próspero y equitativo para todos.",
    btnExplorePhilosophy: "Explorar Filosofía DRACMA con IA ✨", aiModalTitlePhilosophy: "Filosofía DRACMA Explicada por IA ✨",
    visionCard1Title: "Activos Reales, Valor Digital", visionCard1Desc: "Invertimos en activos tangibles y los traemos al mundo digital, ofreciéndote seguridad y potencial de crecimiento.",
    visionCard2Title: "Inteligencia que Potencia", visionCard2Desc: "Usamos IA para tomar decisiones más inteligentes, optimizar operaciones y buscar los mejores rendimientos para nuestra comunidad.",
    visionCard3Title: "Comunidad y Transparencia", visionCard3Desc: "Creemos en el poder de la comunidad. Nuestra DAO asegura que cada miembro tenga voz y que cada operación sea clara y verificable.",
    ecosystemTitle: "El Ecosistema DRACMA: Innovación Conectada", ecosystemSubtitle: "Descubre cómo cada parte de DRACMA trabaja en conjunto para crear valor, ofrecer oportunidades y construir un futuro financiero más sólido y accesible.",
    ecoCard1Title: "Activos Reales Tokenizados (RWA)", ecoCard1Desc: "Inversiones tangibles en oro, bienes raíces de alto rendimiento, energía solar y agricultura sostenible, fraccionados y accesibles vía blockchain.",
    ecoCard2Title: "Inteligencia Artificial (IA)", ecoCard2Desc: "Algoritmos predictivos para la valoración de activos, optimización de flipping, gestión de energía y maximización de la producción agrícola.",
    ecoCard3Title: "Infraestructura Blockchain", ecoCard3Desc: "Plataforma EVM-compatible con soluciones Layer 2 para escalabilidad, seguridad cuántico-resistente y contratos inteligentes auditados.",
    ecoCard4Title: "Gobernanza DAO", ecoCard4Desc: "Toma de decisiones descentralizada donde los holders de tokens $DRC proponen, debaten y votan sobre el futuro del ecosistema.",
    ecoCard5Title: "DRACMA Card & Club", ecoCard5Desc: "Solución Fintech global con membresías exclusivas (Core, Quantum, Photon) que ofrecen beneficios, staking y acceso preferencial.",
    ecoCard6Title: "DRACMA Labs & Academy", ecoCard6Desc: "Investigación y desarrollo en IA, Web4 y optimización de contratos. Formación continua para la comunidad y embajadores.",
    btnExplainAI: "Explicar con IA ✨", 
    crowdfundingTitle: "Crowdfunding P2P DRACMA: Invierte en Fracciones",
    crowdfundingSubtitle: "Democratizamos la inversión en activos de alto valor. Participa con tokens $DRC y sé dueño del futuro, fracción a fracción, de forma directa y transparente.",
    crowdfundingKeyFeaturesTitle: "Características Clave del Crowdfunding P2P",
    crowdfundingFeature1Title: "Propiedad Fraccionada",
    crowdfundingFeature1Desc: "Invierte en partes de activos premium como bienes raíces y energía renovable, haciéndolos accesibles para todos.",
    crowdfundingFeature2Title: "Utilidad del Token $DRC",
    crowdfundingFeature2Desc: "Todas las inversiones, dividendos y gobernanza en la plataforma de crowdfunding se realizan con tokens $DRC.",
    crowdfundingFeature3Title: "Modelo Peer-to-Peer",
    crowdfundingFeature3Desc: "Conexión directa entre creadores de proyectos e inversores, eliminando intermediarios y aumentando la eficiencia.",
    crowdfundingFeature4Title: "Transparencia y Seguridad",
    crowdfundingFeature4Desc: "Cada transacción e inversión se registra en la blockchain, ofreciendo auditoría completa y seguridad inmutable.",
    crowdfundingFeature5Title: "Accesibilidad Mejorada",
    crowdfundingFeature5Desc: "Menores barreras de entrada para diversificar tu portafolio con activos tradicionalmente exclusivos.",
    btnExplainCrowdfundingAI: "Explicar Crowdfunding P2P con IA ✨",
    aiModalTitleCrowdfunding: "IA Explica: Crowdfunding P2P con DRACMA ✨",
    simulatedResponseCrowdfunding: "El Crowdfunding P2P de DRACMA te permite invertir pequeñas cantidades en grandes proyectos, como edificios o plantas solares, usando tokens $DRC. Te conviertes en co-dueño, recibiendo beneficios proporcionales. ¡Es una forma revolucionaria de democratizar la inversión, segura y transparente gracias a la blockchain!",
    crowdfundingActiveProjectsTitle: "Proyectos de Crowdfunding Activos",
    crowdfundingProjectSolarisName: "Expansión Solaris Park II",
    crowdfundingProjectSolarisAsset: "Energía Renovable",
    crowdfundingProjectEcoResidencesName: "EcoResidences Beta",
    crowdfundingProjectEcoResidencesAsset: "Bienes Raíces Sostenibles",
    crowdfundingProjectAgriFutureName: "AgriFuture DAO Fund I",
    crowdfundingAssetTypeAgriculture: "Agricultura Sostenible de Precisión",
    crowdfundingAssetTypeRenewable: "Energía Renovable",
    crowdfundingAssetTypeRealEstate: "Bienes Raíces",
    crowdfundingProjectStatusOpen: "Abierto para Inversión",
    crowdfundingProjectStatusFunded: "Financiado Exitosamente",
    crowdfundingProjectStatusComingSoon: "Próximamente",
    crowdfundingMinInvestmentLabel: "Inversión Mín.:",
    crowdfundingFundingProgressLabel: "Progreso:",
    crowdfundingBtnViewProject: "Ver Detalles e Invertir",
    crowdfundingEstROILabel: "ROI Estimado:",
    crowdfundingROISolar: "8-12% TAE + Créditos Carbono",
    crowdfundingROIRealEstate: "7-10% Rendimiento + Apreciación",
    crowdfundingROIAgriculture: "9-14% TAE + Participación Cosecha",
    crowdfundingDisclaimer: "Nota: Los proyectos mostrados son ilustrativos y con fines de demostración. La participación real está sujeta a términos, condiciones y disponibilidad en la plataforma DRACMA.",
    presaleGoalLabel: "Objetivo:",
    membershipTitle: "Membresías DRACMA: Tu Acceso Exclusivo", membershipSubtitle: "Elige el nivel que mejor se adapte a tus ambiciones y únete a una comunidad de visionarios. Cada membresía abre puertas a beneficios y oportunidades únicas en el ecosistema DRACMA.",
    btnRecommendMembership: "¿Qué membresía me conviene? ✨ Analizar con IA",
    memberTier1Name: "CORE", memberTier1Desc: "Acceso Esencial", memberTierPriceSuffix: "/año",
    memberTier1Feat1: "DRACMA Card Digital CORE", memberTier1Feat2: "Acceso a eventos comunitarios", memberTier1Feat3: "5% bonus en Staking", memberTier1Feat4: "Participación en votaciones DAO", btnJoinCore: "Unirse a CORE",
    tagPopular: "MÁS POPULAR", memberTier2Name: "QUANTUM", memberTier2Desc: "Beneficios Avanzados",
    memberTier2Feat1: "DRACMA Card Física QUANTUM", memberTier2Feat2: "Acceso a eventos QUANTUM", memberTier2Feat3: "10% bonus en Staking", memberTier2Feat4: "Acceso temprano a inversiones RWA", memberTier2Feat5: "Soporte prioritario con IA", memberTier2Feat6: "Redes de contacto exclusivas", btnJoinQuantum: "Unirse a QUANTUM",
    memberTier3Name: "PHOTON", memberTier3Desc: "Experiencia Élite Total",
    memberTier3Feat1: "DRACMA Card VIP PHOTON (Ed. Limitada)", memberTier3Feat2: "Acceso a todos los eventos globales VIP", memberTier3Feat3: "15% bonus en Staking", memberTier3Feat4: "Acceso prioritario a todas las inversiones", memberTier3Feat5: "Concierge personal 24/7", memberTier3Feat6: "Reuniones estratégicas con el equipo", memberTier3Feat7: "Estrategias de inversión a medida", btnJoinPhoton: "Unirse a PHOTON",
    membershipCardTitle: "Tu DRACMA Membership Card", membershipCardSubtitle: "Más que una tarjeta: es tu llave a un mundo de oportunidades. Diseño elegante, tecnología de punta y acceso exclusivo al ecosistema DRACMA.",
    cardType: "MEMBERSHIP", cardHolder: "TITULAR", cardExpires: "EXPIRA", cardBackText: "Propiedad de DRACMA DAO. Uso exclusivo para miembros.\nVisita dracma.org/support para asistencia.", cardBlockchainId: "Blockchain ID:",
    presaleTitle: "DRACMA TOKEN PRESALE", presaleLive: "LIVE", presaleSubtitle: "Asegura tu futuro en el ecosistema DRACMA. Participa en nuestra preventa exclusiva y accede a beneficios únicos como inversor temprano.",
    presaleEndsIn: "LA OPORTUNIDAD TERMINA EN:", countdownDays: "DÍAS", countdownHours: "HORAS", countdownMinutes: "MIN", countdownSeconds: "SEG",
    presaleStatusTitle: "Estado de la Preventa", presaleTokenPrice: "Precio Token:", presaleTotalProgress: "Progreso Total:", presaleTokensSold: "Tokens Vendidos (Preventa):",
    presaleActiveBonus: "Bonos Activos:", 
    presaleBonusPhase1Name: "FASE 1: 15% BONUS", presaleBonusPhase1Info: "¡ÚLTIMOS DÍAS DE LA FASE 1!", 
    presaleBonusPhase2Name: "FASE 2: 10% BONUS", presaleBonusPhase2Info: "¡FASE 2 ACTIVA AHORA!",
    presaleBonusPhase3Name: "FASE 3: 5% BONUS", presaleBonusPhase3Info: "¡APROVECHA LA FASE 3!",
    presaleBonusEndedName: "BONUS FINALIZADO", presaleBonusEndedInfo: "La preventa continúa sin bonus adicional.",
    presaleMinInvestment: "Mínima inversión: $100 USD.", presaleTokenDistribution: "Tokens distribuidos post-TGE con vesting.",
    presaleInvestTitle: "Invierte en el Futuro DRACMA",
    presaleSelectPayment: "1. Selecciona Criptomoneda de Pago:",
    presaleEnterAmount: "2. Ingresa Monto de Inversión",
    btnMax: "MAX", presaleBaseTokens: "Tokens $DRC Base:", presaleCurrentBonus: "Bono Actual", presaleTotalReceive: "Total $DRC a Recibir:",
    btnAnalyzeInvestment: "Analizar Inversión con IA ✨", btnGeneratePitch: "Generar Pitch de Embajador con IA ✨",
    btnConnectAndConfirm: "Pagar usando crypto", presaleAgreement: "Al participar, aceptas nuestros <a>Términos</a> y <a>Acuerdo de Venta de Tokens</a>.",
    tokenDistributionTitle: "Distribución Estratégica del Token $DRC",
    distPresale: "Presale", distPresaleDesc: "Financiamiento inicial y recompensas a early adopters.",
    distLiquidity: "Liquidez", distLiquidityDesc: "Asegurar mercados saludables en DEX y CEX.",
    distStaking: "Staking Rewards", distStakingDesc: "Incentivos para holders (14% APR estimado).",
    distEcosystem: "Ecosistema & Desarrollo", distEcosystemDesc: "Crecimiento, partnerships e innovación continua.",
    roadmapTitle: "Roadmap DRACMA: Trazando el Futuro", roadmapSubtitle: "Nuestra hoja de ruta estratégica, clara y transparente, para construir el holding empresarial descentralizado que definirá la próxima era de valor.",
    roadmapPhase1Title: "Fase 1 (2025): Lanzamiento y Cimientos", roadmapPhase1List: "Lanzamiento de DRACMA DAO y Presale de tokens $DRC.|Primeras adquisiciones de RWA: Flipping inmobiliario piloto.|Implementación del Programa de Staking (14% APR).|Lanzamiento Beta de la DRACMA Card (Digital).|Auditorías iniciales de contratos y reservas.",
    roadmapPhase2Title: "Fase 2 (2026): Expansión y Ecosistema", roadmapPhase2List: "Expansión del marketplace RWA (bienes raíces, energía, agro).|Despliegue de granjas solares y data centers IA.|Integración de proyectos Viviendas DIGNA.|Lanzamiento del mercado de créditos de Carbono (CO₂).|Listado de $DRC en principales exchanges.",
    roadmapPhase3Title: "Fase 3 (2027): Consolidación Global", roadmapPhase3List: "Operaciones expandidas a más de 10 países.|Consolidación de Crowdlending en sectores clave.|Alcance de la neutralidad de carbono.|Crecimiento del ecosistema a valoración de +$10B.|Optimización y ampliación de modelos IA predictivos.",
    roadmapPhase4Title: "Fase 4 (2028-2030): Liderazgo Visionario", roadmapPhase4List: "Desarrollo de Micronations DAO y modelos de autogobernanza.|Meta global de activos tokenizados +$50B.|Implementación completa de soluciones e-Government.|Liderazgo en innovaciones Web4 y IA generativa.|DRACMA como estándar de valor descentralizado.",
    btnRoadmapOutlook: "Analizar Impacto del Roadmap con IA ✨", aiModalTitleRoadmap: "Perspectiva Futura del Roadmap IA ✨",
    ambassadorsTitle: "Programa de Embajadores DRACMA", ambassadorsSubtitle: "Únete a nuestra red de visionarios. Como Embajador DRACMA, serás una pieza clave en la expansión de nuestra comunidad global, compartiendo nuestra misión y siendo recompensado por ayudarnos a construir el futuro del valor.",
    ambassador1Title: "Conector Regional", ambassador1Desc: "Sé la voz de DRACMA en tu comunidad. Organiza, educa y conecta a personas con nuestra visión de un futuro financiero descentralizado.", ambassadorEarnings: "Recompensas Clave", ambassador1Earnings: "Comisiones atractivas + Bonos por crecimiento", btnLearnMore: "Conocer Más",
    tagElite: "ÉLITE", ambassador2Title: "Arquitecto Corporativo", ambassador2Desc: "Establece puentes con el mundo empresarial. Facilita alianzas estratégicas e integra las soluciones de DRACMA en organizaciones visionarias.", ambassador2Earnings: "Comisiones significativas + Participación en el éxito", btnApplyNow: "Postular Ahora",
    ambassador3Title: "Mentor Académico", ambassador3Desc: "Comparte tu conocimiento. Impulsa la educación sobre Web3, IA y finanzas descentralizadas a través de DRACMA Academy.", ambassador3Earnings: "Comisiones + Apoyo a la investigación",
    contactTitle: "Conéctate con DRACMA", contactSubtitle: "Estamos aquí para ayudarte. Si tienes preguntas sobre nuestras membresías, oportunidades de inversión o deseas colaborar, no dudes en contactarnos. Juntos, estamos construyendo el futuro.",
    contactFormTitle: "Envíanos tu Consulta", formName: "Nombre Completo", formEmail: "Email de Contacto", formSubject: "Asunto", formMessage: "Tu Mensaje", btnSendMessage: "Enviar Mensaje",
    formNamePlaceholder: "Tu Nombre Completo", formEmailPlaceholder: "tu.email@dominio.com", formMessagePlaceholder: "Escribe tu consulta aquí...",
    subjectMembership: "Consulta de Membresía", subjectInvestment: "Oportunidad de Inversión", subjectPartnership: "Propuesta de Colaboración", subjectPress: "Prensa y Medios", subjectOther: "Otro",
    contactPointsTitle: "Nuestros Canales", contactHQ: "Oficinas Globales", contactHQLocations: "Dubai (DIFC), EAU | Zug, Suiza (Crypto Valley) | Singapur",
    contactEmailDirect: "Email General", contactEmailValue: "info@dracma.org", contactSupport: "Soporte a Miembros", contactSupportDesc: "Disponible 24/7 a través del portal de miembros.", contactFollowUs: "Únete a la Conversación",
    footerDesc: "Un holding empresarial descentralizado con activos del mundo real, impulsado por IA y tecnología blockchain.",
    footerNav: "Navegación", footerResources: "Recursos", footerWhitepaper: "Whitepaper", footerAudits: "Reportes de Auditoría", footerBlog: "Blog (Medium)", faq: "FAQ",
    footerLegal: "Legal", footerTerms: "Términos de Servicio", footerPrivacy: "Política de Privacidad", footerCookies: "Política de Cookies", footerRisk: "Aviso de Riesgo",
    footerCopyright: "© 2025 DRACMA DAO. Todos los derechos reservados. Innovate. Integrate. Inspire.",
    whitepaperModalTitle: "Whitepaper DRACMA – Blueprint v3.0 (2025)", whitepaperAuthorship: "Autoría: DRACMA Core Development & Strategic Unit", whitepaperCopyrightText: "© 2025 DRACMA DAO. El futuro es colaborativo.", 
    whitepaperDisclaimerTitle: "Disclaimer Legal y Proyecciones Futuras",
    whitepaperDisclaimerText: "Este documento es solo para fines informativos y no constituye una oferta de venta ni una solicitud de oferta de compra de ningún valor en ninguna jurisdicción. La información aquí contenida se basa en fuentes consideradas fiables, pero no se garantiza su exactitud ni integridad. Las declaraciones prospectivas implican riesgos e incertidumbres inherentes. Los resultados reales pueden diferir materialmente de los proyectados. Los inversores deben realizar su propia diligencia debida y consultar a sus asesores financieros antes de tomar cualquier decisión de inversión. DRACMA DAO se reserva el derecho de modificar sus planes en cualquier momento.",
    whitepaperIntroTitle: "1.0 Introducción: La Nueva Frontera del Valor Descentralizado",
    whitepaperIntroText: "En la cúspide de una revolución digital sin precedentes, DRACMA emerge como un paradigma transformador en el universo Web3. Nuestra visión es construir un holding empresarial descentralizado que armonice la solidez intrínseca de los Activos del Mundo Real (RWA) con la agilidad y transparencia de la tecnología blockchain, potenciado por la inteligencia artificial (IA) de vanguardia. Este whitepaper es el mapa estelar de DRACMA, detallando nuestra arquitectura tecnológica, estrategia de mercado, tokenomics y el modelo de gobernanza que nos impulsará hacia la democratización del acceso a oportunidades de inversión de alto calibre, fomentando un ecosistema de valor sostenible y crecimiento compartido. Invitamos a visionarios, inversores y constructores a unirse a nosotros en esta travesía para redefinir el futuro del valor.",
    whitepaperFullContentPlaceholder: "Cargando el futuro... El contenido completo del Whitepaper DRACMA v3.0, incluyendo análisis de mercado, tokenomics detallados, arquitectura técnica, equipo y asesores, gobernanza DAO, y proyecciones financieras, estará disponible aquí. Prepárate para sumergirte en el blueprint de la próxima generación de inversión descentralizada.",
    walletConnecting: "CONECTANDO A LA RED DRACMA...", walletSim: "(Simulación. Funcionalidad de wallet multi-cadena en desarrollo.)",
    wrongNetwork: "Red incorrecta. Por favor cambia a BSC.", switchToBSC: "Cambiar a BSC",
    walletNotInstalled: "No se detectó wallet. Por favor instala MetaMask o abre desde tu wallet móvil.",
    installMetaMask: "Instalar MetaMask", yourBalance: "Tu saldo",
    walletSelectTitle: "Conectar Wallet", walletMobileDesc: "Selecciona tu wallet para abrir DRACMA en su navegador integrado.",
    walletOpenInApp: "Abrir en la app", walletDesktopHint: "Instala una extensión de wallet en tu navegador para conectarte.",
    btnBuyTokens: "Comprar Tokens $DRC", btnDisconnectWallet: "Desconectar",
    connectedTo: "Conectado", networkBSC: "BNB Smart Chain",
    txApproving: "Aprobando...", txApprovePending: "Aprobación pendiente...",
    txBuying: "Comprando...", txBuyPending: "Compra pendiente...",
    txSuccess: "¡Compra exitosa!", txFailed: "Transacción fallida",
    txRejected: "Transacción rechazada por el usuario",
    insufficientBalance: "Saldo insuficiente",
    belowMinPurchase: "Monto por debajo del mínimo de compra",
    exceedsMaxPurchase: "Monto excede el máximo de compra",
    presaleEndedMsg: "La preventa ha terminado", presalePausedMsg: "La preventa está pausada actualmente",
    viewOnBSCScan: "Ver en BSCScan", buyMore: "Comprar Más",
    approveStep: "Paso 1: Aprobar", buyStep: "Paso 2: Comprar",
    txPleaseApprove: "Por favor aprueba en MetaMask...", txPleaseConfirm: "Por favor confirma en MetaMask...",
    formSending: "Enviando Mensaje...", formSent: "Mensaje Enviado con Éxito",
    aiModalTitleInvestment: "Análisis de Inversión IA ✨", aiModalTitlePitch: "Pitch de Embajador IA ✨", 
    aiModalTitleEcosystem: "IA Explica: Ecosistema DRACMA ✨", aiModalTitleMembership: "Recomendación de Membresía IA ✨",
    aiModalLoading: "DRACMA IA está analizando... un momento.", aiModalError: "Error al conectar con DRACMA IA. Inténtalo más tarde.",
    btnCopyText: "Copiar Texto", btnCopied: "¡Texto Copiado!",
    altHeroAbstract: "[Representación Abstracta de DRACMA y el futuro del valor]",
    simulatedResponsePhilosophy: `La filosofía de DRACMA se centra en fusionar la estabilidad de activos reales con la innovación de Web3 y IA, creando un ecosistema financiero transparente y accesible para todos. Buscamos empoderar a nuestra comunidad mediante inversiones inteligentes en oro, bienes raíces, energía y agricultura, forjando un futuro próspero y equitativo.`,
    simulatedResponseInvestment: `Tu inversión en la presale de DRACMA parece prometedora. Con el respaldo de activos reales y la potencia de la IA, junto con el atractivo APR de staking, $DRC tiene un gran potencial de crecimiento. ¡Es un excelente momento para unirse a la vanguardia de la innovación financiera!`,
    simulatedResponseAmbassador: `¡Únete a DRACMA y sé pionero en la revolución Web3! Conectamos activos reales con IA y blockchain, ofreciendo staking del 14% y dividendos. Ayúdanos a construir un futuro financiero transparente y rentable para todos. ¡Tu impacto comienza ahora!`,
    simulatedResponseEcosystemDetail: `Este componente es crucial en DRACMA, ya que [menciona un beneficio clave del componente]. Al integrarse con nuestra IA y blockchain, potencia [otro beneficio], ofreciendo a los inversores [un valor tangible]. Es una pieza fundamental para democratizar el acceso a oportunidades de inversión de alta calidad.`,
    simulatedResponseMembershipRec: `Para inversores que inician: CORE es ideal. Para quienes buscan beneficios avanzados y acceso temprano: QUANTUM es perfecto. Para la experiencia élite con atención personalizada y acceso VIP: PHOTON es la elección.`,
    simulatedResponseRoadmapOutlook: `El roadmap de DRACMA traza un camino ambicioso hacia un ecosistema financiero descentralizado y robusto. Si se ejecuta con éxito, DRACMA podría redefinir la inversión en Web3, ofreciendo un estándar de valor tangible y transparente a escala global, e incluso sentar las bases para nuevos modelos de gobernanza.`,
    simulatedResponseContact: `¡Gracias por contactar a DRACMA! Hemos recibido tu mensaje y nuestro equipo se pondrá en contacto contigo a la brevedad. Apreciamos tu interés en construir el futuro del valor con nosotros.`,
    simulatedResponseGeneric: `DRACMA IA está procesando tu solicitud. En un entorno real, recibirías una respuesta detallada basada en el modelo Gemini. Por ahora, esta es una simulación que indica que tu prompt ha sido recibido.`

  },
  en: {
    navVision: "Vision", navEcosystem: "Ecosystem", navCrowdfunding: "P2P Crowdfunding", navMembership: "Membership", navPresale: "Presale", navRoadmap: "Roadmap", navAmbassadors: "Ambassadors", navContact: "Contact",
    btnConnectWallet: "Connect Wallet", srOpenMenu: "Open main menu",
    heroTitleBrand: "DRACMA", heroTitlePhoenix: "The Future of Value, Today.",
    heroSubtitle: "A cutting-edge Web3 holding company merging AI, Blockchain, and tokenized Real World Assets. Invest intelligently and transparently in the new economy.",
    btnJoinPresale: "Join Presale", btnExplore: "Explore Ecosystem",
    visionTitle: "Our Vision: Forging Tomorrow, Together",
    visionSubtitle: "At DRACMA, we believe in a more accessible, transparent, and fair financial future. We don't just envision this future; we are actively building it. We are a team of innovators, strategists, and technologists with a clear mission: to create a Decentralized Business Holding that serves as a bridge between the solidity of traditional assets and the limitless potential of Web3.\nWe use Artificial Intelligence to optimize and Blockchain to secure, transforming real-world assets (RWA)—such as gold, real estate, renewable energy, and sustainable agriculture—into liquid and verifiable investment opportunities.\nOur goal is simple: to empower you. To offer you the tools and platform to participate in the new economy of value, informed and with confidence. DRACMA is more than a project; it's a community investing in a more prosperous and equitable tomorrow for all.",
    btnExplorePhilosophy: "Explore DRACMA Philosophy with AI ✨", aiModalTitlePhilosophy: "AI Explains: DRACMA Philosophy ✨",
    visionCard1Title: "Real Assets, Digital Value", visionCard1Desc: "We invest in tangible assets and bring them to the digital world, offering you security and growth potential.",
    visionCard2Title: "Intelligence that Empowers", visionCard2Desc: "We use AI to make smarter decisions, optimize operations, and seek the best returns for our community.",
    visionCard3Title: "Community and Transparency", visionCard3Desc: "We believe in the power of community. Our DAO ensures every member has a voice and every operation is clear and verifiable.",
    ecosystemTitle: "The DRACMA Ecosystem: Connected Innovation", ecosystemSubtitle: "Discover how each part of DRACMA works together to create value, offer opportunities, and build a more solid and accessible financial future.",
    ecoCard1Title: "Tokenized Real World Assets (RWA)", ecoCard1Desc: "Tangible investments in gold, high-yield real estate, solar energy, and sustainable agriculture, fractionalized and accessible via blockchain.",
    ecoCard2Title: "Artificial Intelligence (AI)", ecoCard2Desc: "Predictive algorithms for asset valuation, flipping optimization, energy management, and maximization of agricultural output.",
    ecoCard3Title: "Blockchain Infrastructure", ecoCard3Desc: "EVM-compatible platform with Layer 2 solutions for scalability, quantum-resistant security, and audited smart contracts.",
    ecoCard4Title: "DAO Governance", ecoCard4Desc: "Decentralized decision-making where $DRC token holders propose, debate, and vote on the ecosystem's future.",
    ecoCard5Title: "DRACMA Card & Club", ecoCard5Desc: "Global Fintech solution with exclusive memberships (Core, Quantum, Photon) offering benefits, staking, and preferential access.",
    ecoCard6Title: "DRACMA Labs & Academy", ecoCard6Desc: "Research and development in AI, Web4, and contract optimization. Continuous training for the community and ambassadors.",
    btnExplainAI: "Explain with AI ✨",
    crowdfundingTitle: "DRACMA P2P Crowdfunding: Invest in Fractions",
    crowdfundingSubtitle: "Democratizing high-value asset investment. Participate with $DRC tokens and own the future, fraction by fraction, directly and transparently.",
    crowdfundingKeyFeaturesTitle: "Key Features of P2P Crowdfunding",
    crowdfundingFeature1Title: "Fractional Ownership",
    crowdfundingFeature1Desc: "Invest in parts of premium assets like real estate and renewable energy, making them accessible to everyone.",
    crowdfundingFeature2Title: "$DRC Token Utility",
    crowdfundingFeature2Desc: "All investments, dividends, and governance on the crowdfunding platform are powered by $DRC tokens.",
    crowdfundingFeature3Title: "Peer-to-Peer Model",
    crowdfundingFeature3Desc: "Direct connection between project originators and investors, cutting out intermediaries and boosting efficiency.",
    crowdfundingFeature4Title: "Transparency & Security",
    crowdfundingFeature4Desc: "Every transaction and investment is recorded on the blockchain, offering full auditability and immutable security.",
    crowdfundingFeature5Title: "Enhanced Accessibility",
    crowdfundingFeature5Desc: "Lower entry barriers to diversify your portfolio with traditionally exclusive, high-potential assets.",
    btnExplainCrowdfundingAI: "Explain P2P Crowdfunding with AI ✨",
    aiModalTitleCrowdfunding: "AI Explains: P2P Crowdfunding with DRACMA ✨",
    simulatedResponseCrowdfunding: "DRACMA's P2P Crowdfunding lets you invest small amounts in big projects, like buildings or solar plants, using $DRC tokens. You become a co-owner, receiving proportional benefits. It's a revolutionary way to democratize investment, safe and transparent thanks to the blockchain!",
    crowdfundingActiveProjectsTitle: "Active Crowdfunding Projects",
    crowdfundingProjectSolarisName: "Solaris Park II Expansion",
    crowdfundingProjectSolarisAsset: "Renewable Energy",
    crowdfundingProjectEcoResidencesName: "EcoResidences Beta",
    crowdfundingProjectEcoResidencesAsset: "Sustainable Real Estate",
    crowdfundingProjectAgriFutureName: "AgriFuture DAO Fund I",
    crowdfundingAssetTypeAgriculture: "Precision Sustainable Agriculture",
    crowdfundingAssetTypeRenewable: "Renewable Energy",
    crowdfundingAssetTypeRealEstate: "Real Estate",
    crowdfundingProjectStatusOpen: "Open for Investment",
    crowdfundingProjectStatusFunded: "Successfully Funded",
    crowdfundingProjectStatusComingSoon: "Coming Soon",
    crowdfundingMinInvestmentLabel: "Min. Investment:",
    crowdfundingFundingProgressLabel: "Progress:",
    crowdfundingBtnViewProject: "View Details & Invest",
    crowdfundingEstROILabel: "Est. ROI:",
    crowdfundingROISolar: "8-12% APR + Carbon Credits",
    crowdfundingROIRealEstate: "7-10% Yield + Appreciation",
    crowdfundingROIAgriculture: "9-14% APR + Harvest Share",
    crowdfundingDisclaimer: "Note: Projects shown are illustrative and for demonstration purposes. Actual participation is subject to terms, conditions, and availability on the DRACMA platform.",
    presaleGoalLabel: "Goal:",
    membershipTitle: "DRACMA Memberships: Your Exclusive Access", membershipSubtitle: "Choose the tier that best suits your ambitions and join a community of visionaries. Each membership unlocks unique benefits and opportunities within the DRACMA ecosystem.",
    btnRecommendMembership: "Which membership suits me? ✨ Analyze with AI",
    memberTier1Name: "CORE", memberTier1Desc: "Essential Access", memberTierPriceSuffix: "/year",
    memberTier1Feat1: "CORE Digital DRACMA Card", memberTier1Feat2: "Access to community events", memberTier1Feat3: "5% Staking Bonus", memberTier1Feat4: "DAO Voting Participation", btnJoinCore: "Join CORE",
    tagPopular: "MOST POPULAR", memberTier2Name: "QUANTUM", memberTier2Desc: "Advanced Benefits",
    memberTier2Feat1: "QUANTUM Physical DRACMA Card", memberTier2Feat2: "Access to QUANTUM events", memberTier2Feat3: "10% Staking Bonus", memberTier2Feat4: "Early Access to RWA Investments", memberTier2Feat5: "Priority AI-driven Support", memberTier2Feat6: "Exclusive Networking Circles", btnJoinQuantum: "Join QUANTUM",
    memberTier3Name: "PHOTON", memberTier3Desc: "Total Elite Experience",
    memberTier3Feat1: "PHOTON VIP DRACMA Card (Limited Ed.)", memberTier3Feat2: "Access to All Global VIP Events", memberTier3Feat3: "15% Staking Bonus", memberTier3Feat4: "Priority Access to All Investments", memberTier3Feat5: "24/7 Personal Concierge", memberTier3Feat6: "Strategic Meetings with Leadership", memberTier3Feat7: "Tailored Investment Strategies", btnJoinPhoton: "Join PHOTON",
    membershipCardTitle: "Your DRACMA Membership Card", membershipCardSubtitle: "More than a card: it's your key to a world of opportunities. Elegant design, cutting-edge technology, and exclusive access to the DRACMA ecosystem.",
    cardType: "MEMBERSHIP", cardHolder: "CARD HOLDER", cardExpires: "EXPIRES", cardBackText: "Property of DRACMA DAO. Exclusive use for members.\nVisit dracma.org/support for assistance.", cardBlockchainId: "Blockchain ID:",
    presaleTitle: "DRACMA TOKEN PRESALE", presaleLive: "LIVE", presaleSubtitle: "Secure your future in the DRACMA ecosystem. Participate in our exclusive presale and access unique benefits as an early investor.",
    presaleEndsIn: "OPPORTUNITY ENDS IN:", countdownDays: "DAYS", countdownHours: "HOURS", countdownMinutes: "MINS", countdownSeconds: "SECS",
    presaleStatusTitle: "Presale Status", presaleTokenPrice: "Token Price:", presaleTotalProgress: "Total Progress:", presaleTokensSold: "Tokens Sold (Presale):",
    presaleActiveBonus: "Active Bonuses:", 
    presaleBonusPhase1Name: "PHASE 1: 15% BONUS", presaleBonusPhase1Info: "LAST DAYS OF PHASE 1!",
    presaleBonusPhase2Name: "PHASE 2: 10% BONUS", presaleBonusPhase2Info: "PHASE 2 ACTIVE NOW!",
    presaleBonusPhase3Name: "PHASE 3: 5% BONUS", presaleBonusPhase3Info: "GET INTO PHASE 3!",
    presaleBonusEndedName: "BONUS ENDED", presaleBonusEndedInfo: "Presale continues without additional bonus.",
    presaleMinInvestment: "Minimum investment: $100 USD.", presaleTokenDistribution: "Tokens distributed post-TGE with vesting.",
    presaleInvestTitle: "Invest in DRACMA's Future",
    presaleSelectPayment: "1. Select Payment Cryptocurrency:",
    presaleEnterAmount: "2. Enter Investment Amount",
    btnMax: "MAX", presaleBaseTokens: "$DRC Base Tokens:", presaleCurrentBonus: "Current Bonus", presaleTotalReceive: "Total $DRC to Receive:",
    btnAnalyzeInvestment: "Analyze Investment with AI ✨", btnGeneratePitch: "Generate Ambassador Pitch with AI ✨",
    btnConnectAndConfirm: "Connect Wallet & Confirm Investment", presaleAgreement: "By participating, you agree to our <a>Terms</a> and <a>Token Sale Agreement</a>.",
    tokenDistributionTitle: "Strategic $DRC Token Distribution",
    distPresale: "Presale", distPresaleDesc: "Initial funding and rewards for early adopters.",
    distLiquidity: "Liquidity", distLiquidityDesc: "Ensuring healthy markets on DEXs and CEXs.",
    distStaking: "Staking Rewards", distStakingDesc: "Incentives for holders (14% APR est.).",
    distEcosystem: "Ecosystem & Development", distEcosystemDesc: "Growth, partnerships, and continuous innovation.",
    roadmapTitle: "DRACMA Roadmap: Charting the Future", roadmapSubtitle: "Our clear and transparent strategic roadmap to build the decentralized business holding that will define the next era of value.",
    roadmapPhase1Title: "Phase 1 (2025): Launch & Foundation", roadmapPhase1List: "DRACMA DAO launch and $DRC token presale.|First RWA acquisitions: Pilot real estate flipping.|Staking Program implementation (14% APR).|Beta launch of DRACMA Card (Digital).|Initial contract and reserve audits.",
    roadmapPhase2Title: "Phase 2 (2026): Expansion & Ecosystem", roadmapPhase2List: "RWA marketplace expansion (real estate, energy, agro).|Deployment of solar farms and AI data centers.|Viviendas DIGNA projects integration.|Launch of Carbon Credits (CO₂) market.|Listing of $DRC on major exchanges.",
    roadmapPhase3Title: "Phase 3 (2027): Global Consolidation", roadmapPhase3List: "Operations expanded to 10+ countries.|Consolidation of Crowdlending in key sectors.|Achieving carbon neutrality.|Ecosystem growth to +$10B valuation.|Optimization and expansion of predictive AI models.",
    roadmapPhase4Title: "Phase 4 (2028-2030): Visionary Leadership", roadmapPhase4List: "Development of Micronations DAO and self-governance models.|Global target of +$50B tokenized assets.|Full implementation of e-Government solutions.|Leadership in Web4 and generative AI innovations.|DRACMA as a standard of decentralized value.",
    btnRoadmapOutlook: "Analyze Roadmap Impact with AI ✨", aiModalTitleRoadmap: "AI Roadmap Future Outlook ✨",
    ambassadorsTitle: "DRACMA Ambassador Program", ambassadorsSubtitle: "Join our elite network of visionaries. As a DRACMA Ambassador, you'll be a key part of expanding our global community, sharing our mission, and being rewarded for helping build the future of value.",
    ambassador1Title: "Regional Connector", ambassador1Desc: "Be the voice of DRACMA in your community. Organize, educate, and connect people to our vision of a decentralized financial future.", ambassadorEarnings: "Key Rewards", ambassador1Earnings: "Attractive commissions + Growth bonuses", btnLearnMore: "Learn More",
    tagElite: "ELITE", ambassador2Title: "Corporate Architect", ambassador2Desc: "Build bridges with the business world. Facilitate strategic alliances and integrate DRACMA solutions into visionary organizations.", ambassador2Earnings: "Significant commissions + Success sharing", btnApplyNow: "Apply Now",
    ambassador3Title: "Academic Mentor", ambassador3Desc: "Share your knowledge. Drive education on Web3, AI, and decentralized finance through DRACMA Academy.", ambassador3Earnings: "Commissions + Research support",
    contactTitle: "Connect with DRACMA", contactSubtitle: "We're here to help. If you have questions about our memberships, investment opportunities, or wish to collaborate, don't hesitate to reach out. Together, we're building the future.",
    contactFormTitle: "Send Us Your Inquiry", formName: "Full Name", formEmail: "Contact Email", formSubject: "Subject", formMessage: "Your Message", btnSendMessage: "Send Message",
    formNamePlaceholder: "Your Full Name", formEmailPlaceholder: "your.email@domain.com", formMessagePlaceholder: "Write your inquiry here...",
    subjectMembership: "Membership Inquiry", subjectInvestment: "Investment Opportunity", subjectPartnership: "Partnership Proposal", subjectPress: "Press & Media", subjectOther: "Other",
    contactPointsTitle: "Our Channels", contactHQ: "Global Offices", contactHQLocations: "Dubai (DIFC), UAE | Zug, Switzerland (Crypto Valley) | Singapore",
    contactEmailDirect: "General Email", contactEmailValue: "info@dracma.org", contactSupport: "Member Support", contactSupportDesc: "Available 24/7 via the member portal.", contactFollowUs: "Join the Conversation",
    footerDesc: "A decentralized business holding with real-world assets, powered by AI and blockchain technology.",
    footerNav: "Navigation", footerResources: "Resources", footerWhitepaper: "Whitepaper", footerAudits: "Audit Reports", footerBlog: "Blog (Medium)", faq: "FAQ",
    footerLegal: "Legal", footerTerms: "Terms of Service", footerPrivacy: "Privacy Policy", footerCookies: "Cookie Policy", footerRisk: "Risk Disclosure",
    footerCopyright: "© 2025 DRACMA DAO. All rights reserved. Innovate. Integrate. Inspire.",
    whitepaperModalTitle: "DRACMA Whitepaper – Blueprint v3.0 (2025)", whitepaperAuthorship: "Authored by: DRACMA Core Development & Strategic Unit", whitepaperCopyrightText: "© 2025 DRACMA DAO. The future is collaborative.",
    whitepaperDisclaimerTitle: "Legal Disclaimer & Forward-Looking Statements",
    whitepaperDisclaimerText: "This document is for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any security in any jurisdiction. The information herein is based on sources believed to be reliable but is not guaranteed as to accuracy or completeness. Forward-looking statements involve inherent risks and uncertainties. Actual results may differ materially from those projected. Investors should conduct their own due diligence and consult their financial advisors before making any investment decisions. DRACMA DAO reserves the right to modify its plans at any time.",
    whitepaperIntroTitle: "1.0 Introduction: The New Frontier of Decentralized Value",
    whitepaperIntroText: "At the cusp of an unprecedented digital revolution, DRACMA emerges as a transformative paradigm in the Web3 universe. Our vision is to build a decentralized business holding that harmonizes the intrinsic stability of Real-World Assets (RWA) with the agility and transparency of blockchain technology, supercharged by cutting-edge Artificial Intelligence (AI). This whitepaper is DRACMA's star chart, detailing our technological architecture, go-to-market strategy, tokenomics, and the governance model that will propel us towards democratizing access to high-caliber investment opportunities, fostering an ecosystem of sustainable value and shared growth. We invite visionaries, investors, and builders to join us on this journey to redefine the future of value.",
    whitepaperFullContentPlaceholder: "Loading the future... The full content of the DRACMA Whitepaper v3.0, including market analysis, detailed tokenomics, technical architecture, team and advisors, DAO governance, and financial projections, will be available here. Prepare to dive into the blueprint of the next generation of decentralized investment.",
    walletConnecting: "CONNECTING TO DRACMA NETWORK...", walletSim: "(Simulation. Multi-chain wallet functionality in development.)",
    wrongNetwork: "Wrong network. Please switch to BSC.", switchToBSC: "Switch to BSC",
    walletNotInstalled: "No wallet detected. Please install MetaMask or open from your mobile wallet.",
    installMetaMask: "Install MetaMask", yourBalance: "Your Balance",
    walletSelectTitle: "Connect Wallet", walletMobileDesc: "Select your wallet to open DRACMA in its built-in browser.",
    walletOpenInApp: "Open in app", walletDesktopHint: "Install a wallet browser extension to connect.",
    btnBuyTokens: "Buy $DRC Tokens", btnDisconnectWallet: "Disconnect",
    connectedTo: "Connected", networkBSC: "BNB Smart Chain",
    txApproving: "Approving...", txApprovePending: "Approval pending...",
    txBuying: "Purchasing...", txBuyPending: "Purchase pending...",
    txSuccess: "Purchase successful!", txFailed: "Transaction failed",
    txRejected: "Transaction rejected by user",
    insufficientBalance: "Insufficient balance",
    belowMinPurchase: "Amount below minimum purchase",
    exceedsMaxPurchase: "Amount exceeds maximum purchase",
    presaleEndedMsg: "The presale has ended", presalePausedMsg: "The presale is currently paused",
    viewOnBSCScan: "View on BSCScan", buyMore: "Buy More",
    approveStep: "Step 1: Approve", buyStep: "Step 2: Purchase",
    txPleaseApprove: "Please approve in MetaMask...", txPleaseConfirm: "Please confirm in MetaMask...",
    formSending: "Sending Message...", formSent: "Message Sent Successfully",
    aiModalTitleInvestment: "AI Investment Analysis ✨", aiModalTitlePitch: "AI Ambassador Pitch ✨", 
    aiModalTitleEcosystem: "AI Explains: DRACMA Ecosystem ✨", aiModalTitleMembership: "AI Membership Recommendation ✨",
    aiModalLoading: "DRACMA AI is analyzing... one moment.", aiModalError: "Error connecting to DRACMA AI. Please try again later.",
    btnCopyText: "Copy Text", btnCopied: "Text Copied!",
    altHeroAbstract: "[Abstract Representation of DRACMA and the future of value]",
    simulatedResponsePhilosophy: `DRACMA's philosophy centers on merging the stability of real assets with Web3 and AI innovation, creating a transparent, accessible financial ecosystem for all. We aim to empower our community through smart investments in gold, real estate, energy, and agriculture, forging a prosperous and equitable future.`,
    simulatedResponseInvestment: `Your investment in DRACMA's presale looks promising. Backed by real assets and AI power, along with attractive staking APR, $DRC holds significant growth potential. It's an excellent time to join the forefront of financial innovation!`,
    simulatedResponseAmbassador: `Join DRACMA and pioneer the Web3 revolution! We connect real assets with AI and blockchain, offering 14% APR staking and dividends. Help us build a transparent, profitable financial future for everyone. Your impact starts now!`,
    simulatedResponseEcosystemDetail: `This component is crucial in DRACMA as it [mentions a key benefit of the component]. By integrating with our AI and blockchain, it enhances [another benefit], offering investors [tangible value]. It's a cornerstone for democratizing access to high-quality investment opportunities.`,
    simulatedResponseMembershipRec: `For investors starting out: CORE is ideal. For those seeking advanced benefits and early access: QUANTUM is perfect. For the elite experience with personalized attention and VIP access: PHOTON is the choice.`,
    simulatedResponseRoadmapOutlook: `DRACMA's roadmap charts an ambitious path towards a robust, decentralized financial ecosystem. If successfully executed, DRACMA could redefine Web3 investment, offering a global standard for tangible, transparent value, and even lay groundwork for new governance models.`,
    simulatedResponseContact: `Thank you for contacting DRACMA! We have received your message and our team will be in touch with you shortly. We appreciate your interest in building the future of value with us.`,
    simulatedResponseGeneric: `DRACMA AI is processing your request. In a real environment, you would receive a detailed response from the Gemini model. For now, this is a simulation indicating your prompt has been received.`
  },
  fr: { 
    navVision: "Vision", navEcosystem: "Écosystème", navCrowdfunding: "Crowdfunding P2P", navMembership: "Adhésion", navPresale: "Prévente", navRoadmap: "Feuille de route", navAmbassadors: "Ambassadeurs", navContact: "Contact",
    btnConnectWallet: "Connecter Portefeuille", heroTitlePhoenix: "Le Futur de la Valeur", 
    btnJoinPresale: "Rejoindre Prévente", btnExplore: "Explorer", visionTitle: "Notre Vision",
    crowdfundingTitle: "Crowdfunding P2P DRACMA", crowdfundingSubtitle: "Investissez dans des fractions.",
    crowdfundingKeyFeaturesTitle: "Caractéristiques Clés",
    crowdfundingFeature1Title: "Propriété Fractionnée", crowdfundingFeature1Desc: "Accessible à tous.",
    crowdfundingFeature2Title: "Jeton $DRC Utile", crowdfundingFeature2Desc: "Alimente la plateforme.",
    crowdfundingFeature3Title: "Modèle P2P", crowdfundingFeature3Desc: "Direct et efficace.",
    crowdfundingFeature4Title: "Transparence & Sécurité", crowdfundingFeature4Desc: "Avec Blockchain.",
    crowdfundingFeature5Title: "Accessibilité Améliorée", crowdfundingFeature5Desc: "Portefeuilles diversifiés.",
    btnExplainCrowdfundingAI: "Expliquer P2P avec IA ✨", aiModalTitleCrowdfunding: "IA Explique: P2P DRACMA ✨",
    simulatedResponseCrowdfunding: "Le Crowdfunding P2P de DRACMA vous permet d'investir dans de grands projets avec de petites sommes de tokens $DRC. Devenez copropriétaire et recevez des avantages. C'est sûr et transparent grâce à la blockchain !",
    crowdfundingActiveProjectsTitle: "Projets Actifs",
    crowdfundingProjectSolarisName: "Expansion Solaris II", crowdfundingProjectSolarisAsset: "Énergie Renouvelable",
    crowdfundingProjectEcoResidencesName: "EcoResidences Beta", crowdfundingProjectEcoResidencesAsset: "Immobilier Durable",
    crowdfundingProjectAgriFutureName: "AgriFuture DAO I", crowdfundingAssetTypeAgriculture: "Agriculture Durable",
    crowdfundingAssetTypeRenewable: "Énergie Renouvelable", crowdfundingAssetTypeRealEstate: "Immobilier",
    crowdfundingProjectStatusOpen: "Ouvert", crowdfundingProjectStatusFunded: "Financé", crowdfundingProjectStatusComingSoon: "Bientôt",
    crowdfundingMinInvestmentLabel: "Invest. Min.:", crowdfundingFundingProgressLabel: "Progrès:",
    crowdfundingBtnViewProject: "Voir & Investir", crowdfundingEstROILabel: "ROI Est.:",
    crowdfundingROISolar: "8-12% TAE", crowdfundingROIRealEstate: "7-10% Rendement", crowdfundingROIAgriculture: "9-14% TAE",
    crowdfundingDisclaimer: "Note: Projets illustratifs.", presaleGoalLabel: "But:",
    btnCopyText: "Copier le texte", btnCopied: "Copié !",
    wrongNetwork: "Mauvais réseau. Veuillez passer au BSC.", switchToBSC: "Passer au BSC",
    walletNotInstalled: "Aucun wallet détecté. Installez MetaMask ou ouvrez depuis votre wallet mobile.", installMetaMask: "Installer MetaMask",
    walletSelectTitle: "Connecter Wallet", walletMobileDesc: "Sélectionnez votre wallet pour ouvrir DRACMA dans son navigateur intégré.",
    walletOpenInApp: "Ouvrir dans l'app", walletDesktopHint: "Installez une extension wallet dans votre navigateur.",
    yourBalance: "Votre solde", btnBuyTokens: "Acheter des tokens $DRC", btnDisconnectWallet: "Déconnecter",
    connectedTo: "Connecté", networkBSC: "BNB Smart Chain",
    txApproving: "Approbation...", txApprovePending: "Approbation en cours...",
    txBuying: "Achat...", txBuyPending: "Achat en cours...",
    txSuccess: "Achat réussi !", txFailed: "Transaction échouée", txRejected: "Transaction rejetée par l'utilisateur",
    insufficientBalance: "Solde insuffisant", belowMinPurchase: "Montant inférieur au minimum",
    exceedsMaxPurchase: "Montant supérieur au maximum",
    presaleEndedMsg: "La prévente est terminée", presalePausedMsg: "La prévente est actuellement en pause",
    viewOnBSCScan: "Voir sur BSCScan", buyMore: "Acheter Plus",
    approveStep: "Étape 1: Approuver", buyStep: "Étape 2: Acheter",
    txPleaseApprove: "Veuillez approuver dans MetaMask...", txPleaseConfirm: "Veuillez confirmer dans MetaMask..."
  },
  hi: { 
    navVision: "दृष्टिकोण", navEcosystem: "पारिस्थितिकी तंत्र", navCrowdfunding: "P2P क्राउडफंडिंग", navMembership: "सदस्यता", navPresale: "प्रीसेल", navRoadmap: "रोडमैप", navAmbassadors: "राजदूत", navContact: "संपर्क",
    btnConnectWallet: "वॉलेट कनेक्ट करें", heroTitlePhoenix: "मूल्य का भविष्य",
    crowdfundingTitle: "DRACMA P2P क्राउडफंडिंग", crowdfundingSubtitle: "अंशों में निवेश करें।",
    crowdfundingKeyFeaturesTitle: "मुख्य विशेषताएं",
    crowdfundingFeature1Title: "आंशिक स्वामित्व", crowdfundingFeature1Desc: "सभी के लिए सुलभ।",
    crowdfundingFeature2Title: "$DRC टोकन उपयोगिता", crowdfundingFeature2Desc: "प्लेटफ़ॉर्म को शक्ति।",
    crowdfundingFeature3Title: "पीयर-टू-पीयर मॉडल", crowdfundingFeature3Desc: "प्रत्यक्ष और कुशल।",
    crowdfundingFeature4Title: "पारदर्शिता और सुरक्षा", crowdfundingFeature4Desc: "ब्लॉकचेन के साथ।",
    crowdfundingFeature5Title: "बेहतर पहुंच", crowdfundingFeature5Desc: "विविध पोर्टफोलियो।",
    btnExplainCrowdfundingAI: "AI के साथ P2P समझाएं ✨", aiModalTitleCrowdfunding: "AI समझाता है: P2P DRACMA ✨",
    simulatedResponseCrowdfunding: "DRACMA का P2P क्राउडफंडिंग आपको $DRC टोकन का उपयोग करके बड़ी परियोजनाओं में छोटी रकम का निवेश करने देता है। आप सह-मालिक बन जाते हैं, आनुपातिक लाभ प्राप्त करते हैं। यह ब्लॉकचेन की बदौलत निवेश को लोकतंत्रीकरण करने का एक क्रांतिकारी तरीका है, सुरक्षित और पारदर्शी!",
    crowdfundingActiveProjectsTitle: "सक्रिय परियोजनाएं",
    crowdfundingProjectSolarisName: "सोलारिस पार्क II विस्तार", crowdfundingProjectSolarisAsset: "नवीकरणीय ऊर्जा",
    crowdfundingProjectEcoResidencesName: "इकोरेसिडेंसेस बीटा", crowdfundingProjectEcoResidencesAsset: "टिकाऊ रियल एस्टेट",
    crowdfundingProjectAgriFutureName: "एग्रीफ्यूचर DAO फंड I", crowdfundingAssetTypeAgriculture: "सटीक टिकाऊ कृषि",
    crowdfundingAssetTypeRenewable: "नवीकरणीय ऊर्जा", crowdfundingAssetTypeRealEstate: "रियल एस्टेट",
    crowdfundingProjectStatusOpen: "निवेश के लिए खुला", crowdfundingProjectStatusFunded: "सफलतापूर्वक वित्तपोषित", crowdfundingProjectStatusComingSoon: "जल्द आ रहा है",
    crowdfundingMinInvestmentLabel: "न्यूनतम निवेश:", crowdfundingFundingProgressLabel: "प्रगति:",
    crowdfundingBtnViewProject: "विवरण देखें और निवेश करें", crowdfundingEstROILabel: "अनुमानित ROI:",
    crowdfundingROISolar: "8-12% APR", crowdfundingROIRealEstate: "7-10% यील्ड", crowdfundingROIAgriculture: "9-14% APR",
    crowdfundingDisclaimer: "नोट: परियोजनाएं केवल उदाहरण के लिए हैं।", presaleGoalLabel: "लक्ष्य:",
    btnCopyText: "टेक्स्ट कॉपी करें", btnCopied: "कॉपी किया गया!",
    wrongNetwork: "गलत नेटवर्क। कृपया BSC पर स्विच करें।", switchToBSC: "BSC पर स्विच करें",
    walletNotInstalled: "कोई वॉलेट नहीं मिला। MetaMask इंस्टॉल करें या मोबाइल वॉलेट से खोलें।", installMetaMask: "MetaMask स्थापित करें",
    walletSelectTitle: "वॉलेट कनेक्ट करें", walletMobileDesc: "DRACMA को इसके बिल्ट-इन ब्राउज़र में खोलने के लिए अपना वॉलेट चुनें।",
    walletOpenInApp: "ऐप में खोलें", walletDesktopHint: "कनेक्ट करने के लिए वॉलेट ब्राउज़र एक्सटेंशन इंस्टॉल करें।",
    yourBalance: "आपका शेष", btnBuyTokens: "$DRC टोकन खरीदें", btnDisconnectWallet: "डिस्कनेक्ट",
    connectedTo: "कनेक्टेड", networkBSC: "BNB स्मार्ट चेन",
    txApproving: "स्वीकृति हो रही है...", txApprovePending: "स्वीकृति लंबित...",
    txBuying: "खरीद रहा है...", txBuyPending: "खरीद लंबित...",
    txSuccess: "खरीद सफल!", txFailed: "लेनदेन विफल", txRejected: "उपयोगकर्ता द्वारा लेनदेन अस्वीकार",
    insufficientBalance: "अपर्याप्त शेष", belowMinPurchase: "न्यूनतम खरीद से कम",
    exceedsMaxPurchase: "अधिकतम खरीद से अधिक",
    presaleEndedMsg: "प्रीसेल समाप्त हो गई है", presalePausedMsg: "प्रीसेल वर्तमान में रुकी हुई है",
    viewOnBSCScan: "BSCScan पर देखें", buyMore: "और खरीदें",
    approveStep: "चरण 1: स्वीकृति", buyStep: "चरण 2: खरीदें",
    txPleaseApprove: "कृपया MetaMask में स्वीकृत करें...", txPleaseConfirm: "कृपया MetaMask में पुष्टि करें..."
  },
  ar: { 
    navVision: "رؤيتنا", navEcosystem: "النظام البيئي", navCrowdfunding: "التمويل الجماعي P2P", navMembership: "العضوية", navPresale: "ما قبل البيع", navRoadmap: "خريطة الطريق", navAmbassadors: "السفراء", navContact: "اتصال",
    btnConnectWallet: "ربط المحفظة", heroTitlePhoenix: "مستقبل القيمة",
    crowdfundingTitle: "DRACMA للتمويل الجماعي P2P", crowdfundingSubtitle: "استثمر في أجزاء.",
    crowdfundingKeyFeaturesTitle: "الميزات الرئيسية",
    crowdfundingFeature1Title: "ملكية جزئية", crowdfundingFeature1Desc: "متاحة للجميع.",
    crowdfundingFeature2Title: "فائدة رمز $DRC", crowdfundingFeature2Desc: "يشغل المنصة.",
    crowdfundingFeature3Title: "نموذج نظير إلى نظير", crowdfundingFeature3Desc: "مباشر وفعال.",
    crowdfundingFeature4Title: "الشفافية والأمان", crowdfundingFeature4Desc: "مع البلوكشين.",
    crowdfundingFeature5Title: "إمكانية وصول محسنة", crowdfundingFeature5Desc: "محافظ متنوعة.",
    btnExplainCrowdfundingAI: "شرح P2P مع الذكاء الاصطناعي ✨", aiModalTitleCrowdfunding: "الذكاء الاصطناعي يشرح: P2P DRACMA ✨",
    simulatedResponseCrowdfunding: "يتيح لك التمويل الجماعي P2P من DRACMA استثمار مبالغ صغيرة في مشاريع كبيرة، مثل المباني أو محطات الطاقة الشمسية، باستخدام رموز $DRC. تصبح مالكًا مشاركًا، وتحصل على مزايا متناسبة. إنها طريقة ثورية لإضفاء الطابع الديمقراطي على الاستثمار، آمنة وشفافة بفضل البلوكشين!",
    crowdfundingActiveProjectsTitle: "المشاريع النشطة",
    crowdfundingProjectSolarisName: "توسعة سولاريس بارك II", crowdfundingProjectSolarisAsset: "الطاقة المتجددة",
    crowdfundingProjectEcoResidencesName: "إيكو ريزيدنس بيتا", crowdfundingProjectEcoResidencesAsset: "العقارات المستدامة",
    crowdfundingProjectAgriFutureName: "صندوق AgriFuture DAO I", crowdfundingAssetTypeAgriculture: "الزراعة المستدامة الدقيقة",
    crowdfundingAssetTypeRenewable: "الطاقة المتجددة", crowdfundingAssetTypeRealEstate: "العقارات",
    crowdfundingProjectStatusOpen: "مفتوح للاستثمار", crowdfundingProjectStatusFunded: "تم تمويله بنجاح", crowdfundingProjectStatusComingSoon: "قريبا",
    crowdfundingMinInvestmentLabel: "الحد الأدنى للاستثمار:", crowdfundingFundingProgressLabel: "التقدم:",
    crowdfundingBtnViewProject: "عرض التفاصيل والاستثمار", crowdfundingEstROILabel: "العائد على الاستثمار المقدر:",
    crowdfundingROISolar: "8-12% APR", crowdfundingROIRealEstate: "7-10% عائد", crowdfundingROIAgriculture: "9-14% APR",
    crowdfundingDisclaimer: "ملاحظة: المشاريع المعروضة هي لأغراض توضيحية فقط.", presaleGoalLabel: "الهدف:",
    btnCopyText: "نسخ النص", btnCopied: "تم النسخ!",
    wrongNetwork: "شبكة خاطئة. يرجى التبديل إلى BSC.", switchToBSC: "التبديل إلى BSC",
    walletNotInstalled: "لم يتم اكتشاف محفظة. يرجى تثبيت MetaMask أو الفتح من محفظتك المحمولة.", installMetaMask: "تثبيت MetaMask",
    walletSelectTitle: "توصيل المحفظة", walletMobileDesc: "اختر محفظتك لفتح DRACMA في متصفحها المدمج.",
    walletOpenInApp: "فتح في التطبيق", walletDesktopHint: "قم بتثبيت إضافة محفظة في متصفحك للاتصال.",
    yourBalance: "رصيدك", btnBuyTokens: "شراء رموز $DRC", btnDisconnectWallet: "قطع الاتصال",
    connectedTo: "متصل", networkBSC: "سلسلة BNB الذكية",
    txApproving: "جاري الموافقة...", txApprovePending: "الموافقة معلقة...",
    txBuying: "جاري الشراء...", txBuyPending: "الشراء معلق...",
    txSuccess: "تم الشراء بنجاح!", txFailed: "فشلت المعاملة", txRejected: "تم رفض المعاملة من قبل المستخدم",
    insufficientBalance: "رصيد غير كافي", belowMinPurchase: "المبلغ أقل من الحد الأدنى للشراء",
    exceedsMaxPurchase: "المبلغ يتجاوز الحد الأقصى للشراء",
    presaleEndedMsg: "انتهى البيع المسبق", presalePausedMsg: "البيع المسبق متوقف حاليًا",
    viewOnBSCScan: "عرض على BSCScan", buyMore: "شراء المزيد",
    approveStep: "الخطوة 1: الموافقة", buyStep: "الخطوة 2: الشراء",
    txPleaseApprove: "يرجى الموافقة في MetaMask...", txPleaseConfirm: "يرجى التأكيد في MetaMask..."
  },
  ru: { 
    navVision: "Видение", navEcosystem: "Экосистема", navCrowdfunding: "P2P Краудфандинг", navMembership: "Членство", navPresale: "Предпродажа", navRoadmap: "Дорожная карта", navAmbassadors: "Амбассадоры", navContact: "Контакт",
    btnConnectWallet: "Подключить кошелек", heroTitlePhoenix: "Будущее Ценности",
    crowdfundingTitle: "DRACMA P2P Краудфандинг", crowdfundingSubtitle: "Инвестируйте в доли.",
    crowdfundingKeyFeaturesTitle: "Ключевые особенности",
    crowdfundingFeature1Title: "Долевое владение", crowdfundingFeature1Desc: "Доступно для всех.",
    crowdfundingFeature2Title: "Полезность токена $DRC", crowdfundingFeature2Desc: "Питает платформу.",
    crowdfundingFeature3Title: "Модель P2P", crowdfundingFeature3Desc: "Прямой и эффективный.",
    crowdfundingFeature4Title: "Прозрачность и безопасность", crowdfundingFeature4Desc: "С блокчейном.",
    crowdfundingFeature5Title: "Улучшенная доступность", crowdfundingFeature5Desc: "Разнообразные портфели.",
    btnExplainCrowdfundingAI: "Объяснить P2P с помощью ИИ ✨", aiModalTitleCrowdfunding: "ИИ объясняет: P2P DRACMA ✨",
    simulatedResponseCrowdfunding: "P2P-краудфандинг DRACMA позволяет инвестировать небольшие суммы в крупные проекты, такие как здания или солнечные электростанции, используя токены $DRC. Вы становитесь совладельцем, получая пропорциональные выгоды. Это революционный способ демократизации инвестиций, безопасный и прозрачный благодаря блокчейну!",
    crowdfundingActiveProjectsTitle: "Активные проекты",
    crowdfundingProjectSolarisName: "Расширение Солярис Парк II", crowdfundingProjectSolarisAsset: "Возобновляемая энергия",
    crowdfundingProjectEcoResidencesName: "ЭкоРезиденции Бета", crowdfundingProjectEcoResidencesAsset: "Устойчивая недвижимость",
    crowdfundingProjectAgriFutureName: "Фонд AgriFuture DAO I", crowdfundingAssetTypeAgriculture: "Точное устойчивое сельское хозяйство",
    crowdfundingAssetTypeRenewable: "Возобновляемая энергия", crowdfundingAssetTypeRealEstate: "Недвижимость",
    crowdfundingProjectStatusOpen: "Открыт для инвестиций", crowdfundingProjectStatusFunded: "Успешно профинансирован", crowdfundingProjectStatusComingSoon: "Скоро",
    crowdfundingMinInvestmentLabel: "Мин. инвестиции:", crowdfundingFundingProgressLabel: "Прогресс:",
    crowdfundingBtnViewProject: "Посмотреть детали и инвестировать", crowdfundingEstROILabel: "Ожидаемый ROI:",
    crowdfundingROISolar: "8-12% годовых", crowdfundingROIRealEstate: "7-10% доходность", crowdfundingROIAgriculture: "9-14% годовых",
    crowdfundingDisclaimer: "Примечание: Представленные проекты являются иллюстративными.", presaleGoalLabel: "Цель:",
    btnCopyText: "Скопировать текст", btnCopied: "Скопировано!",
    wrongNetwork: "Неверная сеть. Переключитесь на BSC.", switchToBSC: "Переключиться на BSC",
    walletNotInstalled: "Кошелек не обнаружен. Установите MetaMask или откройте из мобильного кошелька.", installMetaMask: "Установить MetaMask",
    walletSelectTitle: "Подключить кошелек", walletMobileDesc: "Выберите кошелек, чтобы открыть DRACMA во встроенном браузере.",
    walletOpenInApp: "Открыть в приложении", walletDesktopHint: "Установите расширение кошелька в браузере для подключения.",
    yourBalance: "Ваш баланс", btnBuyTokens: "Купить токены $DRC", btnDisconnectWallet: "Отключить",
    connectedTo: "Подключено", networkBSC: "BNB Smart Chain",
    txApproving: "Одобрение...", txApprovePending: "Ожидание одобрения...",
    txBuying: "Покупка...", txBuyPending: "Ожидание покупки...",
    txSuccess: "Покупка успешна!", txFailed: "Транзакция не удалась", txRejected: "Транзакция отклонена пользователем",
    insufficientBalance: "Недостаточный баланс", belowMinPurchase: "Сумма ниже минимальной покупки",
    exceedsMaxPurchase: "Сумма превышает максимальную покупку",
    presaleEndedMsg: "Предпродажа завершена", presalePausedMsg: "Предпродажа приостановлена",
    viewOnBSCScan: "Посмотреть на BSCScan", buyMore: "Купить ещё",
    approveStep: "Шаг 1: Одобрить", buyStep: "Шаг 2: Купить",
    txPleaseApprove: "Одобрите в MetaMask...", txPleaseConfirm: "Подтвердите в MetaMask..."
  },
  zh: { 
    navVision: "愿景", navEcosystem: "生态系统", navCrowdfunding: "P2P众筹", navMembership: "会员资格", navPresale: "预售", navRoadmap: "路线图", navAmbassadors: "大使", navContact: "联系方式",
    btnConnectWallet: "连接钱包", heroTitlePhoenix: "价值的未来",
    crowdfundingTitle: "DRACMA P2P 众筹", crowdfundingSubtitle: "投资于股份。",
    crowdfundingKeyFeaturesTitle: "主要特点",
    crowdfundingFeature1Title: "部分所有权", crowdfundingFeature1Desc: "人人可参与。",
    crowdfundingFeature2Title: "$DRC 代币效用", crowdfundingFeature2Desc: "为平台提供动力。",
    crowdfundingFeature3Title: "P2P模式", crowdfundingFeature3Desc: "直接高效。",
    crowdfundingFeature4Title: "透明与安全", crowdfundingFeature4Desc: "与区块链结合。",
    crowdfundingFeature5Title: "增强的可访问性", crowdfundingFeature5Desc: "多样化的投资组合。",
    btnExplainCrowdfundingAI: "用 AI 解释 P2P ✨", aiModalTitleCrowdfunding: "AI 解释：P2P DRACMA ✨",
    simulatedResponseCrowdfunding: "DRACMA 的 P2P 众筹让您可以使用 $DRC 代币向大型项目（如建筑物或太阳能发电厂）投入少量资金。您将成为共同所有者，按比例获得收益。这是一种革命性的投资民主化方式，得益于区块链，既安全又透明！",
    crowdfundingActiveProjectsTitle: "进行中的项目",
    crowdfundingProjectSolarisName: "Solaris Park II 扩建", crowdfundingProjectSolarisAsset: "可再生能源",
    crowdfundingProjectEcoResidencesName: "生态住宅 Beta", crowdfundingProjectEcoResidencesAsset: "可持续房地产",
    crowdfundingProjectAgriFutureName: "AgriFuture DAO 基金 I", crowdfundingAssetTypeAgriculture: "精准可持续农业",
    crowdfundingAssetTypeRenewable: "可再生能源", crowdfundingAssetTypeRealEstate: "房地产",
    crowdfundingProjectStatusOpen: "开放投资", crowdfundingProjectStatusFunded: "成功融资", crowdfundingProjectStatusComingSoon: "即将推出",
    crowdfundingMinInvestmentLabel: "最低投资额：", crowdfundingFundingProgressLabel: "进度：",
    crowdfundingBtnViewProject: "查看详情并投资", crowdfundingEstROILabel: "预计投资回报率：",
    crowdfundingROISolar: "8-12% 年化收益率", crowdfundingROIRealEstate: "7-10% 收益率", crowdfundingROIAgriculture: "9-14% 年化收益率",
    crowdfundingDisclaimer: "注：所示项目仅供参考。", presaleGoalLabel: "目标：",
    btnCopyText: "复制文本", btnCopied: "已复制!",
    wrongNetwork: "网络错误。请切换到BSC。", switchToBSC: "切换到BSC",
    walletNotInstalled: "未检测到钱包。请安装MetaMask或从移动钱包打开。", installMetaMask: "安装MetaMask",
    walletSelectTitle: "连接钱包", walletMobileDesc: "选择您的钱包以在其内置浏览器中打开DRACMA。",
    walletOpenInApp: "在应用中打开", walletDesktopHint: "在浏览器中安装钱包扩展以连接。",
    yourBalance: "您的余额", btnBuyTokens: "购买$DRC代币", btnDisconnectWallet: "断开连接",
    connectedTo: "已连接", networkBSC: "BNB智能链",
    txApproving: "审批中...", txApprovePending: "审批待确认...",
    txBuying: "购买中...", txBuyPending: "购买待确认...",
    txSuccess: "购买成功！", txFailed: "交易失败", txRejected: "用户拒绝交易",
    insufficientBalance: "余额不足", belowMinPurchase: "金额低于最低购买额",
    exceedsMaxPurchase: "金额超过最高购买额",
    presaleEndedMsg: "预售已结束", presalePausedMsg: "预售当前暂停",
    viewOnBSCScan: "在BSCScan上查看", buyMore: "继续购买",
    approveStep: "步骤1：授权", buyStep: "步骤2：购买",
    txPleaseApprove: "请在MetaMask中授权...", txPleaseConfirm: "请在MetaMask中确认..."
  }
};


export const VISION_CARDS_DATA: VisionCardData[] = [
    { iconClass: "fas fa-gem", gradientClass: "bg-gradient-to-br from-brand-accent-gold to-yellow-400", titleKey: "visionCard1Title", descKey: "visionCard1Desc", shadowClass: "shadow-gold-glow" },
    { iconClass: "fas fa-brain", gradientClass: "bg-gradient-to-br from-brand-primary to-blue-400", titleKey: "visionCard2Title", descKey: "visionCard2Desc", shadowClass: "shadow-primary-glow" },
    { iconClass: "fas fa-users", gradientClass: "bg-gradient-to-br from-brand-secondary to-green-400", titleKey: "visionCard3Title", descKey: "visionCard3Desc", shadowClass: "shadow-secondary-glow" },
];

export const ECOSYSTEM_CARDS_DATA: EcosystemCardData[] = [
    { iconClass: "fas fa-landmark", colorClass: "brand-accent-gold-text", titleKey: "ecoCard1Title", descKey: "ecoCard1Desc", aiButtonKey: "btnExplainAI" },
    { iconClass: "fas fa-microchip", colorClass: "brand-primary-text", titleKey: "ecoCard2Title", descKey: "ecoCard2Desc", aiButtonKey: "btnExplainAI" },
    { iconClass: "fas fa-cubes", colorClass: "brand-secondary-text", titleKey: "ecoCard3Title", descKey: "ecoCard3Desc", aiButtonKey: "btnExplainAI" },
    { iconClass: "fas fa-vote-yea", colorClass: "text-green-500", titleKey: "ecoCard4Title", descKey: "ecoCard4Desc", aiButtonKey: "btnExplainAI" },
    { iconClass: "fas fa-credit-card", colorClass: "brand-accent-gold-text", titleKey: "ecoCard5Title", descKey: "ecoCard5Desc", aiButtonKey: "btnExplainAI" },
    { iconClass: "fas fa-flask", colorClass: "brand-primary-text", titleKey: "ecoCard6Title", descKey: "ecoCard6Desc", aiButtonKey: "btnExplainAI" },
];

export const CROWDFUNDING_FEATURES_DATA: CrowdfundingFeatureData[] = [
  { iconClass: "fas fa-chart-pie", titleKey: "crowdfundingFeature1Title", descKey: "crowdfundingFeature1Desc", colorClass: "brand-primary-text", bgColorClass: "bg-brand-primary-bg-light" },
  { iconClass: "fas fa-coins", titleKey: "crowdfundingFeature2Title", descKey: "crowdfundingFeature2Desc", colorClass: "brand-accent-gold-text", bgColorClass: "bg-brand-accent-gold-bg-light" },
  { iconClass: "fas fa-users-cog", titleKey: "crowdfundingFeature3Title", descKey: "crowdfundingFeature3Desc", colorClass: "brand-secondary-text", bgColorClass: "bg-brand-secondary-bg-light" },
  { iconClass: "fas fa-shield-alt", titleKey: "crowdfundingFeature4Title", descKey: "crowdfundingFeature4Desc", colorClass: "text-blue-500", bgColorClass: "bg-blue-500-bg-light" },
  { iconClass: "fas fa-hand-holding-seedling", titleKey: "crowdfundingFeature5Title", descKey: "crowdfundingFeature5Desc", colorClass: "text-green-500", bgColorClass: "bg-green-500-bg-light" },
];

export const CROWDFUNDING_PROJECTS_DATA: CrowdfundingProjectData[] = [
  {
    id: "solaris01",
    imagePlaceholder: "600x400/0D1117/7DF9FF?text=Solaris+Park+II",
    nameKey: "crowdfundingProjectSolarisName",
    assetTypeKey: "crowdfundingAssetTypeRenewable",
    fundingGoalDRC: 5000000, 
    fundingGoalUSD: 1000000, 
    currentFundingDRC: 2350000,
    minInvestmentDRC: 500, 
    estimatedROIKey: "crowdfundingROISolar", 
    statusKey: "crowdfundingProjectStatusOpen",
    statusColorClass: "bg-green-500",
  },
  {
    id: "ecores01",
    imagePlaceholder: "600x400/0D1117/FBBF24?text=EcoResidences+Beta",
    nameKey: "crowdfundingProjectEcoResidencesName",
    assetTypeKey: "crowdfundingAssetTypeRealEstate",
    fundingGoalDRC: 10000000, 
    fundingGoalUSD: 2000000,
    currentFundingDRC: 8500000,
    minInvestmentDRC: 1000, 
    estimatedROIKey: "crowdfundingROIRealEstate", 
    statusKey: "crowdfundingProjectStatusOpen",
    statusColorClass: "bg-green-500",
  },
  {
    id: "agri01",
    imagePlaceholder: "600x400/0D1117/10B981?text=AgriFuture+DAO+I",
    nameKey: "crowdfundingProjectAgriFutureName",
    assetTypeKey: "crowdfundingAssetTypeAgriculture",
    fundingGoalDRC: 2500000,
    fundingGoalUSD: 500000,
    currentFundingDRC: 2500000,
    minInvestmentDRC: 250,
    estimatedROIKey: "crowdfundingROIAgriculture", 
    statusKey: "crowdfundingProjectStatusFunded",
    statusColorClass: "bg-brand-primary",
  }
];


export const MEMBERSHIP_TIERS_DATA: MembershipTierData[] = [
    {
        nameKey: "memberTier1Name", descKey: "memberTier1Desc", price: "$1,000", priceSuffixKey: "memberTierPriceSuffix",
        features: [
            { key: "memberTier1Feat1", iconClass: "fas fa-check-circle text-brand-secondary" }, { key: "memberTier1Feat2", iconClass: "fas fa-check-circle text-brand-secondary" },
            { key: "memberTier1Feat3", iconClass: "fas fa-check-circle text-brand-secondary" }, { key: "memberTier1Feat4", iconClass: "fas fa-check-circle text-brand-secondary" }
        ],
        buttonKey: "btnJoinCore", buttonClass: "w-full btn-secondary py-2.5 border-brand-accent-gold/70 text-brand-accent-gold/90 hover:text-brand-background hover:bg-brand-accent-gold",
        gradientClass: "bg-gradient-to-br from-gray-100 to-gray-200", textColorClass: "text-brand-text-primary"
    },
    {
        nameKey: "memberTier2Name", descKey: "memberTier2Desc", price: "$5,000", priceSuffixKey: "memberTierPriceSuffix",
        features: [
            { key: "memberTier2Feat1", iconClass: "fas fa-star text-brand-accent-gold" }, { key: "memberTier2Feat2", iconClass: "fas fa-star text-brand-accent-gold" },
            { key: "memberTier2Feat3", iconClass: "fas fa-star text-brand-accent-gold" }, { key: "memberTier2Feat4", iconClass: "fas fa-star text-brand-accent-gold" },
            { key: "memberTier2Feat5", iconClass: "fas fa-star text-brand-accent-gold" }, { key: "memberTier2Feat6", iconClass: "fas fa-star text-brand-accent-gold" }
        ],
        buttonKey: "btnJoinQuantum", buttonClass: "w-full btn-primary py-2.5",
        isPopular: true, popularTagKey: "tagPopular",
        gradientClass: "bg-gradient-to-br from-brand-primary to-blue-400", textColorClass: "text-white",
        borderColorClass: "border-brand-primary", shadowClass: "shadow-primary-glow"
    },
    {
        nameKey: "memberTier3Name", descKey: "memberTier3Desc", price: "$25,000", priceSuffixKey: "memberTierPriceSuffix",
        features: [
            { key: "memberTier3Feat1", iconClass: "fas fa-atom text-brand-secondary" }, { key: "memberTier3Feat2", iconClass: "fas fa-atom text-brand-secondary" },
            { key: "memberTier3Feat3", iconClass: "fas fa-atom text-brand-secondary" }, { key: "memberTier3Feat4", iconClass: "fas fa-atom text-brand-secondary" },
            { key: "memberTier3Feat5", iconClass: "fas fa-atom text-brand-secondary" }, { key: "memberTier3Feat6", iconClass: "fas fa-atom text-brand-secondary" },
            { key: "memberTier3Feat7", iconClass: "fas fa-atom text-brand-secondary" }
        ],
        buttonKey: "btnJoinPhoton", buttonClass: "w-full btn-secondary py-2.5 border-brand-secondary text-brand-secondary hover:text-white",
        gradientClass: "bg-gradient-to-br from-brand-secondary to-green-400", textColorClass: "text-white"
    }
];

export const TOKEN_DISTRIBUTION_DATA: TokenDistributionItem[] = [
    { percentage: 20, colorClass: "bg-brand-accent-gold", nameKey: "distPresale", descKey: "distPresaleDesc" },
    { percentage: 30, colorClass: "bg-brand-secondary", nameKey: "distLiquidity", descKey: "distLiquidityDesc" },
    { percentage: 15, colorClass: "bg-brand-primary", nameKey: "distStaking", descKey: "distStakingDesc" },
    { percentage: 35, colorClass: "bg-green-500", nameKey: "distEcosystem", descKey: "distEcosystemDesc" },
];

export const ROADMAP_DATA: RoadmapItemData[] = [
    { iconClass: "fas fa-rocket", titleKey: "roadmapPhase1Title", listKey: "roadmapPhase1List", itemIconBgClass: "bg-brand-accent-gold", itemIconShadowClass: "shadow-gold-glow", itemTitleColorClass: "brand-accent-gold-text" },
    { iconClass: "fas fa-cogs", titleKey: "roadmapPhase2Title", listKey: "roadmapPhase2List", itemIconBgClass: "bg-brand-primary", itemIconShadowClass: "shadow-primary-glow", itemTitleColorClass: "brand-primary-text" },
    { iconClass: "fas fa-globe-americas", titleKey: "roadmapPhase3Title", listKey: "roadmapPhase3List", itemIconBgClass: "bg-brand-secondary", itemIconShadowClass: "shadow-secondary-glow", itemTitleColorClass: "brand-secondary-text" },
    { iconClass: "fas fa-infinity", titleKey: "roadmapPhase4Title", listKey: "roadmapPhase4List", itemIconBgClass: "bg-gradient-to-r from-green-400 to-teal-400", itemIconShadowClass: "shadow-[0_0_15px_rgba(74,222,128,0.5)]", itemTitleColorClass: "text-green-500" },
];

export const AMBASSADORS_DATA: AmbassadorTierData[] = [
    {
        iconClass: "fas fa-satellite-dish", iconBgGradientClass: "bg-gradient-to-br from-brand-accent-gold to-yellow-400", iconShadowClass: "shadow-gold-glow",
        titleKey: "ambassador1Title", descKey: "ambassador1Desc", rewardsTitleKey: "ambassadorEarnings", rewardsDescKey: "ambassador1Earnings",
        buttonKey: "btnLearnMore", buttonClass: "w-full btn-secondary py-2.5 border-brand-accent-gold/70 text-brand-accent-gold/90 hover:text-brand-background hover:bg-brand-accent-gold text-sm"
    },
    {
        iconClass: "fas fa-network-wired", iconBgGradientClass: "bg-gradient-to-br from-brand-primary to-blue-400", iconShadowClass: "shadow-primary-glow",
        titleKey: "ambassador2Title", descKey: "ambassador2Desc", rewardsTitleKey: "ambassadorEarnings", rewardsDescKey: "ambassador2Earnings",
        buttonKey: "btnApplyNow", buttonClass: "w-full btn-primary py-2.5 text-sm",
        isElite: true, eliteTagKey: "tagElite", eliteBgClass: "bg-brand-primary"
    },
    {
        iconClass: "fas fa-chalkboard-teacher", iconBgGradientClass: "bg-gradient-to-br from-brand-secondary to-green-400", iconShadowClass: "shadow-secondary-glow",
        titleKey: "ambassador3Title", descKey: "ambassador3Desc", rewardsTitleKey: "ambassadorEarnings", rewardsDescKey: "ambassador3Earnings",
        buttonKey: "btnLearnMore", buttonClass: "w-full btn-secondary py-2.5 border-brand-secondary text-brand-secondary hover:text-white text-sm"
    }
];

export const CONTACT_POINTS_DATA: ContactPoint[] = [
    { iconClass: "fas fa-map-marker-alt", iconBgGradient: "bg-gradient-to-br from-brand-primary to-blue-400", iconShadow: "shadow-primary-glow", titleKey: "contactHQ", descKey: "contactHQLocations" },
    { iconClass: "fas fa-envelope", iconBgGradient: "bg-gradient-to-br from-brand-primary to-blue-400", iconShadow: "shadow-primary-glow", titleKey: "contactEmailDirect", descKey: "contactEmailValue", link: "mailto:info@dracma.org", isEmail: true },
    { iconClass: "fas fa-headset", iconBgGradient: "bg-gradient-to-br from-brand-primary to-blue-400", iconShadow: "shadow-primary-glow", titleKey: "contactSupport", descKey: "contactSupportDesc" }
];

export const SOCIAL_LINKS_DATA: SocialLink[] = [
    { label: "Twitter", iconClass: "fab fa-twitter", href: "https://x.com/dracma_community", hoverColorClass: "hover:text-brand-accent-gold" },
    { label: "Telegram", iconClass: "fab fa-telegram", href: "https://t.me/dracma_updates", hoverColorClass: "hover:text-brand-primary" },
    { label: "Discord", iconClass: "fab fa-discord", href: "#", hoverColorClass: "hover:text-brand-secondary" },
    { label: "Medium", iconClass: "fab fa-medium", href: "#", hoverColorClass: "hover:text-green-500" },
    { label: "LinkedIn", iconClass: "fab fa-linkedin-in", href: "#", hoverColorClass: "hover:text-brand-text-primary" } 
];

export const FOOTER_SECTIONS_DATA: FooterSection[] = [
    {
        titleKey: "footerNav", titleColorClass: "brand-accent-gold-text",
        links: [
            { key: "navVision", href: "#vision" }, { key: "navEcosystem", href: "#ecosystem" },
            { key: "navCrowdfunding", href: "#crowdfunding"}, { key: "navMembership", href: "#membership" }, 
            { key: "navPresale", href: "#presale" }, { key: "navRoadmap", href: "#roadmap" }, 
            { key: "navAmbassadors", href: "#ambassadors" }
        ]
    },
    {
        titleKey: "footerResources", titleColorClass: "brand-primary-text",
        links: [
            { key: "footerWhitepaper", href: "#whitepaper", isWhitepaperModalTrigger: true }, { key: "footerAudits", href: "#" },
            { key: "footerBlog", href: "#" }, { key: "faq", href: "#" } 
        ]
    },
    {
        titleKey: "footerLegal", titleColorClass: "brand-secondary-text",
        links: [
            { key: "footerTerms", href: "#" }, { key: "footerPrivacy", href: "#" },
            { key: "footerCookies", href: "#" }, { key: "footerRisk", href: "#" }
        ]
    }
];

export const FOOTER_SOCIAL_LINKS: SocialLink[] = [
    { label: "Twitter", iconClass: "fab fa-twitter fa-lg", href: "https://x.com/dracma_community", hoverColorClass: "hover:text-brand-accent-gold" },
    { label: "Telegram", iconClass: "fab fa-telegram fa-lg", href: "https://t.me/dracma_updates", hoverColorClass: "hover:text-brand-primary" },
    { label: "Discord", iconClass: "fab fa-discord fa-lg", href: "#", hoverColorClass: "hover:text-brand-secondary" },
    { label: "Medium", iconClass: "fab fa-medium fa-lg", href: "#", hoverColorClass: "hover:text-green-500" },
    { label: "Github", iconClass: "fab fa-github fa-lg", href: "#", hoverColorClass: "hover:text-brand-text-primary" }
];

export const CONTACT_FORM_SUBJECTS = [
    { key: "subjectMembership", value: "Consulta de Membresía" },
    { key: "subjectInvestment", value: "Oportunidad de Inversión" },
    { key: "subjectPartnership", value: "Propuesta de Colaboración" },
    { key: "subjectPress", value: "Prensa y Medios" },
    { key: "subjectOther", value: "Otro" } // Removed optional trailing comma
];
